"""empty message

Revision ID: 8b07b4f0bc6f
Revises: 2f9ae765e2b5
Create Date: 2024-06-26 19:18:19.630995

"""
from alembic import op
import sqlalchemy as sa
from src.data.stars import dummy_data


# revision identifiers, used by Alembic.
revision = '8b07b4f0bc6f'
down_revision = '2f9ae765e2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    stars = op.create_table(
        'stars',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('mass', sa.String(), nullable=True),
        sa.Column('volume', sa.String(), nullable=True),
        sa.Column('temperature', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('image', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###

    op.bulk_insert(stars, dummy_data)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('stars')
    # ### end Alembic commands ###
