"""empty message

Revision ID: 93ac13531bb5
Revises:
Create Date: 2024-06-26 23:39:16.412769

"""
from alembic import op
import sqlalchemy as sa
from src.data import systems, planets, stars


# revision identifiers, used by Alembic.
revision = '93ac13531bb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    system_table = op.create_table(
        'systems',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name')
    )
    planets_table = op.create_table(
        'planets',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('mass', sa.String(), nullable=True),
        sa.Column('volume', sa.String(), nullable=True),
        sa.Column('temperature', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('image', sa.String(), nullable=True),
        sa.Column('system_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name')
    )
    stars_table = op.create_table(
        'stars',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('mass', sa.String(), nullable=True),
        sa.Column('volume', sa.String(), nullable=True),
        sa.Column('temperature', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('image', sa.String(), nullable=True),
        sa.Column('system_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('system_id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(system_table, systems.dummy_data)

    planets_data = []
    for planet in planets.dummy_data:
        planet['system_id'] = systems.dummy_data[0]['id']
        planets_data.append(planet)
    op.bulk_insert(planets_table, planets_data)

    stars_data = []
    for star in stars.dummy_data:
        star['system_id'] = systems.dummy_data[0]['id']
        stars_data.append(star)
    op.bulk_insert(stars_table, stars_data)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stars')
    op.drop_table('planets')
    op.drop_table('systems')
    # ### end Alembic commands ###
